management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true